FROM ubuntu:devel

RUN apt-get -y update && apt-get install -y lsyncd supervisor && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ADD init.sh /usr/local/bin/init.sh

CMD ["/usr/local/bin/init.sh"]
